version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"


  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service


    depends_on:
      - mongo


  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: product-service


    depends_on:
      - mongo
      - rabbitmq

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - mongo
      - rabbitmq
      - product-service

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "3003:3003"

    depends_on:
      - auth-service
      - product-service
      - order-service

volumes:
  mongo_data:
